use_frameworks!

platform :ios, '8.0'

target 'KPageController_Example' do
  pod 'KPageController', :path => '../'

  target 'KPageController_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
